var searchData=
[
  ['này_20strong_0',['này strong',['../md_PHASE__GUIDE.html#autotoc_md11',1,'&lt;strong&gt;Tại sao cần Phase này?&lt;/strong&gt;'],['../md_PHASE__GUIDE.html#autotoc_md43',1,'&lt;strong&gt;Tại sao cần Phase này?&lt;/strong&gt;'],['../md_PHASE__GUIDE.html#autotoc_md22',1,'&lt;strong&gt;Tại sao cần Phase này?&lt;/strong&gt;'],['../md_PHASE__GUIDE.html#autotoc_md33',1,'&lt;strong&gt;Tại sao cần Phase này?&lt;/strong&gt;']]],
  ['nói_20strong_20_3a_1',['&lt;strong&gt;A. Nghe thấy giọng nói&lt;/strong&gt;:',['../md_TASKS__VI.html#autotoc_md126',1,'']]],
  ['nút_20ptt_20push_20to_20talk_20→_20esp32_20strong_2',['&lt;strong&gt;3. Nút PTT (Push-to-Talk) → ESP32&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md284',1,'']]],
  ['nếu_20vẫn_20nhỏ_20strong_3',['&lt;strong&gt;Bước 3: Nếu Vẫn Nhỏ&lt;/strong&gt;',['../md_VOLUME__GUIDE.html#autotoc_md261',1,'']]],
  ['nền_20tảng_20kiểm_20tra_20audio_20loopback_4',['nền tảng kiểm tra audio loopback',['../md_TASKS__VI.html#autotoc_md112',1,'✅ Phase 1: Nền Tảng &amp; Kiểm Tra Audio Loopback'],['../md_tasks.html#autotoc_md104',1,'✅ Phase 1: Nền Tảng &amp; Kiểm Tra Audio Loopback']]],
  ['nối_20chi_20tiết_5',['🔌 Sơ Đồ Kết Nối Chi Tiết',['../md_WIRING__GUIDE.html#autotoc_md279',1,'']]],
  ['nối_20chung_20bclk_20và_20ws_20strong_6',['&lt;strong&gt;2. Nối chung BCLK và WS&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md296',1,'']]],
  ['nối_20phần_20cứng_20strong_20xem_20wiring_5fguide_20md_20_3a_7',['&lt;strong&gt;Kết nối phần cứng&lt;/strong&gt; (xem WIRING_GUIDE.md):',['../md_TASKS__VI.html#autotoc_md118',1,'']]],
  ['nối_20strong_20_3a_8',['&lt;strong&gt;Kiểm tra kết nối&lt;/strong&gt;:',['../md_WIRING__GUIDE.html#autotoc_md291',1,'']]],
  ['network_20entities_9',['Network Entities',['../md_data-model.html#autotoc_md1',1,'']]],
  ['network_20protocol_10',['2.2 Packet Structure (Network Protocol)',['../md_plan.html#autotoc_md69',1,'']]],
  ['nghị_11',['&lt;strong&gt;1. Hardware Gain (MAX98357A Module)&lt;/strong&gt; ⭐ Khuyến nghị',['../md_VOLUME__GUIDE.html#autotoc_md243',1,'']]],
  ['nghị_20strong_20_3a_12',['&lt;strong&gt;Khuyến nghị&lt;/strong&gt;:',['../md_VOLUME__GUIDE.html#autotoc_md273',1,'']]],
  ['nghe_20thấy_20gì_20strong_13',['&lt;strong&gt;Vấn đề 1: Không nghe thấy gì&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md306',1,'']]],
  ['nghe_20thấy_20gì_20từ_20speaker_20strong_14',['nghe thấy gì từ speaker strong',['../md_TASKS__VI.html#autotoc_md130',1,'&lt;strong&gt;Vấn đề 1: Không nghe thấy gì từ Speaker&lt;/strong&gt;'],['../md_TASKS__VI.html#autotoc_md198',1,'&lt;strong&gt;Vấn đề 1: Không nghe thấy gì từ Speaker&lt;/strong&gt;']]],
  ['nghe_20thấy_20giọng_20nói_20strong_20_3a_15',['&lt;strong&gt;A. Nghe thấy giọng nói&lt;/strong&gt;:',['../md_TASKS__VI.html#autotoc_md126',1,'']]],
  ['nghe_20thử_20strong_16',['&lt;strong&gt;Test 2: Nghe Thử&lt;/strong&gt;',['../md_VOLUME__GUIDE.html#autotoc_md270',1,'']]],
  ['ngoài_20trời_20outdoor_20strong_17',['&lt;strong&gt;Test B: Ngoài trời (Outdoor)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md164',1,'']]],
  ['nguồn_18',['✅ Checklist Trước Khi Bật Nguồn',['../md_WIRING__GUIDE.html#autotoc_md290',1,'']]],
  ['nguồn_20strong_19',['nguồn strong',['../md_WIRING__GUIDE.html#autotoc_md295',1,'&lt;strong&gt;1. Điện áp nguồn&lt;/strong&gt;'],['../md_WIRING__GUIDE.html#autotoc_md301',1,'&lt;strong&gt;Test 1: Kiểm tra nguồn&lt;/strong&gt;']]],
  ['nguồn_20strong_20_3a_20',['&lt;strong&gt;Kiểm tra nguồn&lt;/strong&gt;:',['../md_WIRING__GUIDE.html#autotoc_md292',1,'']]],
  ['nhà_20indoor_20strong_21',['&lt;strong&gt;Test A: Trong nhà (Indoor)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md163',1,'']]],
  ['nhất_22',['&lt;strong&gt;3. Kết Hợp Hardware + Software&lt;/strong&gt; 🚀 Mạnh nhất',['../md_VOLUME__GUIDE.html#autotoc_md254',1,'']]],
  ['nhận_20được_20packets_20strong_23',['&lt;strong&gt;Vấn đề 2: Không nhận được packets&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md170',1,'']]],
  ['nhận_20packets_20t009_20strong_24',['&lt;strong&gt;Bước 4: Kiểm Tra RX - Nhận Packets (T009)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md153',1,'']]],
  ['nhỏ_20strong_25',['&lt;strong&gt;Bước 3: Nếu Vẫn Nhỏ&lt;/strong&gt;',['../md_VOLUME__GUIDE.html#autotoc_md261',1,'']]],
  ['nhanh_26',['🎯 Tóm Tắt Nhanh',['../md_WIRING__GUIDE.html#autotoc_md315',1,'']]],
  ['nhau_20strong_27',['nhau strong',['../md_TASKS__VI.html#autotoc_md162',1,'&lt;strong&gt;Bước 6: Test Ở Các Môi Trường Khác Nhau&lt;/strong&gt;'],['../md_TASKS__VI.html#autotoc_md225',1,'&lt;strong&gt;Bước 7: Test Ở Khoảng Cách Khác Nhau&lt;/strong&gt;']]],
  ['nhiễu_20noise_20strong_28',['&lt;strong&gt;2. Nhiễu (Noise)&lt;/strong&gt;',['../md_VOLUME__GUIDE.html#autotoc_md265',1,'']]],
  ['noise_20strong_29',['&lt;strong&gt;2. Nhiễu (Noise)&lt;/strong&gt;',['../md_VOLUME__GUIDE.html#autotoc_md265',1,'']]],
  ['non_20functional_20requirements_30',['3. Non-Functional Requirements',['../md_spec.html#autotoc_md92',1,'']]],
  ['now_31',['now',['../md_TASKS__VI.html#autotoc_md140',1,'✅ Phase 2: Giao Tiếp ESP-NOW'],['../md_tasks.html#autotoc_md105',1,'✅ Phase 2: Giao Tiếp ESP-NOW']]],
  ['now_20communication_32',['✅ Phase 2: ESP-NOW Communication',['../md_PHASE__GUIDE.html#autotoc_md20',1,'']]],
  ['now_20init_20failed_20strong_33',['&lt;strong&gt;Vấn đề 1: ESP-NOW init failed&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md168',1,'']]],
  ['now_20strong_20✅_34',['&lt;strong&gt;T006: Initialize WiFi &amp; ESP-NOW&lt;/strong&gt; ✅',['../md_PHASE__GUIDE.html#autotoc_md24',1,'']]],
  ['now_20vs_20udp_20broadcast_35',['1. Protocol: ESP-NOW vs UDP Broadcast',['../md_research.html#autotoc_md79',1,'']]],
  ['now_20walkie_20talkie_36',['now walkie talkie',['../md_TASKS__VI.html',1,'Danh Sách Công Việc: ESP32 ESP-NOW Walkie-Talkie'],['../md_tasks.html',1,'Danh Sách Công Việc: ESP32 ESP-NOW Walkie-Talkie'],['../md_spec.html',1,'Feature Specification: ESP32 ESP-NOW Walkie-Talkie'],['../md_plan.html',1,'Implementation Plan: ESP32 ESP-NOW Walkie-Talkie']]]
];
