var searchData=
[
  ['kết_0',['🎯 Tổng Kết',['../md_TASKS__VI.html#autotoc_md236',1,'']]],
  ['kết_20các_20phase_1',['📊 Tổng Kết Các Phase',['../md_PHASE__GUIDE.html#autotoc_md51',1,'']]],
  ['kết_20hợp_20hardware_20software_20strong_20🚀_20mạnh_20nhất_2',['&lt;strong&gt;3. Kết Hợp Hardware + Software&lt;/strong&gt; 🚀 Mạnh nhất',['../md_VOLUME__GUIDE.html#autotoc_md254',1,'']]],
  ['kết_20nối_20chi_20tiết_3',['🔌 Sơ Đồ Kết Nối Chi Tiết',['../md_WIRING__GUIDE.html#autotoc_md279',1,'']]],
  ['kết_20nối_20phần_20cứng_20strong_20xem_20wiring_5fguide_20md_20_3a_4',['&lt;strong&gt;Kết nối phần cứng&lt;/strong&gt; (xem WIRING_GUIDE.md):',['../md_TASKS__VI.html#autotoc_md118',1,'']]],
  ['kết_20nối_20strong_20_3a_5',['&lt;strong&gt;Kiểm tra kết nối&lt;/strong&gt;:',['../md_WIRING__GUIDE.html#autotoc_md291',1,'']]],
  ['kết_20quả_20phase_201_20strong_20_3a_6',['&lt;strong&gt;Kết quả Phase 1&lt;/strong&gt;:',['../md_PHASE__GUIDE.html#autotoc_md18',1,'']]],
  ['kết_20quả_20phase_202_20strong_20_3a_7',['&lt;strong&gt;Kết quả Phase 2&lt;/strong&gt;:',['../md_PHASE__GUIDE.html#autotoc_md29',1,'']]],
  ['kết_20quả_20phase_203_20strong_20_3a_8',['&lt;strong&gt;Kết quả Phase 3&lt;/strong&gt;:',['../md_PHASE__GUIDE.html#autotoc_md39',1,'']]],
  ['kết_20quả_20phase_204_20strong_20_3a_9',['&lt;strong&gt;Kết quả Phase 4&lt;/strong&gt;:',['../md_PHASE__GUIDE.html#autotoc_md49',1,'']]],
  ['khác_20nhau_20strong_10',['khác nhau strong',['../md_TASKS__VI.html#autotoc_md162',1,'&lt;strong&gt;Bước 6: Test Ở Các Môi Trường Khác Nhau&lt;/strong&gt;'],['../md_TASKS__VI.html#autotoc_md225',1,'&lt;strong&gt;Bước 7: Test Ở Khoảng Cách Khác Nhau&lt;/strong&gt;']]],
  ['không_20nghe_20thấy_20gì_20strong_11',['&lt;strong&gt;Vấn đề 1: Không nghe thấy gì&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md306',1,'']]],
  ['không_20nghe_20thấy_20gì_20từ_20speaker_20strong_12',['không nghe thấy gì từ speaker strong',['../md_TASKS__VI.html#autotoc_md198',1,'&lt;strong&gt;Vấn đề 1: Không nghe thấy gì từ Speaker&lt;/strong&gt;'],['../md_TASKS__VI.html#autotoc_md130',1,'&lt;strong&gt;Vấn đề 1: Không nghe thấy gì từ Speaker&lt;/strong&gt;']]],
  ['không_20nhận_20được_20packets_20strong_13',['&lt;strong&gt;Vấn đề 2: Không nhận được packets&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md170',1,'']]],
  ['không_20phản_20ứng_20strong_14',['&lt;strong&gt;Vấn đề 1: PTT không phản ứng&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md228',1,'']]],
  ['khảo_15',['📸 Hình Ảnh Tham Khảo',['../md_WIRING__GUIDE.html#autotoc_md311',1,'']]],
  ['khi_20bật_20nguồn_16',['✅ Checklist Trước Khi Bật Nguồn',['../md_WIRING__GUIDE.html#autotoc_md290',1,'']]],
  ['khi_20hàn_17',['🧪 Test Sau Khi Hàn',['../md_WIRING__GUIDE.html#autotoc_md300',1,'']]],
  ['khi_20sửa_20strong_20_3a_18',['&lt;strong&gt;Sau khi sửa&lt;/strong&gt;:',['../md_VOLUME__GUIDE.html#autotoc_md252',1,'']]],
  ['khi_20tx_20strong_19',['&lt;strong&gt;Vấn đề 2: Vẫn có feedback khi TX&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md230',1,'']]],
  ['khoảng_20cách_20khác_20nhau_20strong_20',['&lt;strong&gt;Bước 7: Test Ở Khoảng Cách Khác Nhau&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md225',1,'']]],
  ['khuyến_20nghị_21',['&lt;strong&gt;1. Hardware Gain (MAX98357A Module)&lt;/strong&gt; ⭐ Khuyến nghị',['../md_VOLUME__GUIDE.html#autotoc_md243',1,'']]],
  ['khuyến_20nghị_20strong_20_3a_22',['&lt;strong&gt;Khuyến nghị&lt;/strong&gt;:',['../md_VOLUME__GUIDE.html#autotoc_md273',1,'']]],
  ['kiểm_20thử_20phase_201_23',['🧪 Hướng Dẫn Kiểm Thử Phase 1',['../md_TASKS__VI.html#autotoc_md115',1,'']]],
  ['kiểm_20thử_20phase_202_24',['🧪 Hướng Dẫn Kiểm Thử Phase 2',['../md_TASKS__VI.html#autotoc_md143',1,'']]],
  ['kiểm_20thử_20phase_203_25',['🧪 Hướng Dẫn Kiểm Thử Phase 3',['../md_TASKS__VI.html#autotoc_md179',1,'']]],
  ['kiểm_20thử_20phase_204_26',['🧪 Hướng Dẫn Kiểm Thử Phase 4',['../md_TASKS__VI.html#autotoc_md209',1,'']]],
  ['kiểm_20tra_20audio_20loopback_27',['kiểm tra audio loopback',['../md_TASKS__VI.html#autotoc_md112',1,'✅ Phase 1: Nền Tảng &amp; Kiểm Tra Audio Loopback'],['../md_tasks.html#autotoc_md104',1,'✅ Phase 1: Nền Tảng &amp; Kiểm Tra Audio Loopback']]],
  ['kiểm_20tra_20audio_20loopback_20strong_28',['&lt;strong&gt;Test 3: Kiểm tra Audio Loopback&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md303',1,'']]],
  ['kiểm_20tra_20kết_20nối_20strong_20_3a_29',['&lt;strong&gt;Kiểm tra kết nối&lt;/strong&gt;:',['../md_WIRING__GUIDE.html#autotoc_md291',1,'']]],
  ['kiểm_20tra_20nguồn_20strong_30',['&lt;strong&gt;Test 1: Kiểm tra nguồn&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md301',1,'']]],
  ['kiểm_20tra_20nguồn_20strong_20_3a_31',['&lt;strong&gt;Kiểm tra nguồn&lt;/strong&gt;:',['../md_WIRING__GUIDE.html#autotoc_md292',1,'']]],
  ['kiểm_20tra_20ptt_20button_20strong_32',['&lt;strong&gt;Test 2: Kiểm tra PTT Button&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md302',1,'']]],
  ['kiểm_20tra_20rf_20link_20quality_20t010_20strong_33',['&lt;strong&gt;Bước 5: Kiểm Tra RF Link Quality (T010)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md155',1,'']]],
  ['kiểm_20tra_20rms_20strong_34',['&lt;strong&gt;Test 1: Kiểm tra RMS&lt;/strong&gt;',['../md_VOLUME__GUIDE.html#autotoc_md269',1,'']]],
  ['kiểm_20tra_20rx_20nhận_20packets_20t009_20strong_35',['&lt;strong&gt;Bước 4: Kiểm Tra RX - Nhận Packets (T009)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md153',1,'']]],
  ['kiểm_20tra_20tx_20gửi_20packets_20t008_20strong_36',['&lt;strong&gt;Bước 3: Kiểm Tra TX - Gửi Packets (T008)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md151',1,'']]],
  ['kiện_37',['📋 Danh Sách Linh Kiện',['../md_WIRING__GUIDE.html#autotoc_md277',1,'']]]
];
