var searchData=
[
  ['lên_202_20esp32_20strong_0',['&lt;strong&gt;Bước 1: Flash Firmware Lên 2 ESP32&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md147',1,'']]],
  ['lõi_1',['1. Core Workflow (Quy trình cốt lõi)',['../md_SpecKit__Commands.html#autotoc_md100',1,'']]],
  ['lược_20test_20strong_2',['&lt;strong&gt;3. Testing Strategy (Chiến lược test)&lt;/strong&gt;',['../md_PHASE__GUIDE.html#autotoc_md56',1,'']]],
  ['lượng_3',['lượng',['../md_VOLUME__GUIDE.html#autotoc_md242',1,'🔊 3 Cách Tăng Âm Lượng'],['../md_VOLUME__GUIDE.html#autotoc_md268',1,'🧪 Test Âm Lượng']]],
  ['lượng_20hỗ_20trợ_4',['2. Quality &amp; Support (Chất lượng &amp; Hỗ trợ)',['../md_SpecKit__Commands.html#autotoc_md101',1,'']]],
  ['lượng_20loa_5',['Hướng Dẫn Tăng Âm Lượng Loa',['../md_VOLUME__GUIDE.html',1,'']]],
  ['lưu_20ý_20quan_20trọng_6',['lưu ý quan trọng',['../md_VOLUME__GUIDE.html#autotoc_md263',1,'⚠️ Lưu Ý Quan Trọng'],['../md_WIRING__GUIDE.html#autotoc_md294',1,'🔧 Lưu Ý Quan Trọng']]],
  ['lệ_20mất_20gói_20tin_20strong_7',['&lt;strong&gt;Test 2: Packet Loss (Tỷ lệ mất gói tin)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md158',1,'']]],
  ['l_20r_20của_20inmp441_20strong_8',['&lt;strong&gt;4. Chân L/R của INMP441&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md298',1,'']]],
  ['latency_20độ_20trễ_20strong_9',['&lt;strong&gt;Bước 7: Đo Latency (Độ trễ)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md195',1,'']]],
  ['latency_20calculation_10',['2.3 Memory Strategy &amp; Latency Calculation',['../md_plan.html#autotoc_md70',1,'']]],
  ['latency_20optimization_20t017_20strong_11',['&lt;strong&gt;Bước 5: Test Latency Optimization (T017)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md221',1,'']]],
  ['latency_20quá_20cao_20200ms_20strong_12',['&lt;strong&gt;Vấn đề 3: Latency quá cao (&gt;200ms)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md202',1,'']]],
  ['latency_20strong_13',['&lt;strong&gt;T017: Optimize Latency&lt;/strong&gt;',['../md_PHASE__GUIDE.html#autotoc_md47',1,'']]],
  ['learning_20curve_20học_20từng_20bước_20strong_14',['&lt;strong&gt;4. Learning Curve (Học từng bước)&lt;/strong&gt;',['../md_PHASE__GUIDE.html#autotoc_md57',1,'']]],
  ['led_20button_20drivers_20strong_20✅_15',['&lt;strong&gt;T002: GPIO and LED/Button Drivers&lt;/strong&gt; ✅',['../md_PHASE__GUIDE.html#autotoc_md14',1,'']]],
  ['led_20trạng_20thái_20→_20esp32_20strong_16',['&lt;strong&gt;4. LED Trạng Thái → ESP32&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md286',1,'']]],
  ['led_20và_20button_20t002_20strong_17',['&lt;strong&gt;Bước 2: Test LED và Button (T002)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md121',1,'']]],
  ['led_5factive_5flevel_18',['LED_ACTIVE_LEVEL',['../board__pinout_8h.html#a30877db42defe2775a9b6fbccca21850',1,'board_pinout.h']]],
  ['linh_20hoạt_19',['&lt;strong&gt;2. Software Gain (Trong Code)&lt;/strong&gt; 🎚️ Linh hoạt',['../md_VOLUME__GUIDE.html#autotoc_md248',1,'']]],
  ['linh_20kiện_20',['📋 Danh Sách Linh Kiện',['../md_WIRING__GUIDE.html#autotoc_md277',1,'']]],
  ['link_20quality_20t010_20strong_21',['&lt;strong&gt;Bước 5: Kiểm Tra RF Link Quality (T010)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md155',1,'']]],
  ['link_20strong_20⏳_22',['&lt;strong&gt;T010: Verify RF Link&lt;/strong&gt; ⏳',['../md_PHASE__GUIDE.html#autotoc_md28',1,'']]],
  ['loa_23',['Hướng Dẫn Tăng Âm Lượng Loa',['../md_VOLUME__GUIDE.html',1,'']]],
  ['local_20test_24',['Phase 2: Audio Loopback (Local Test)',['../md_plan.html#autotoc_md73',1,'']]],
  ['log_20rms_20thay_20đổi_20strong_20_3a_25',['&lt;strong&gt;B. Log RMS thay đổi&lt;/strong&gt;:',['../md_TASKS__VI.html#autotoc_md127',1,'']]],
  ['log_20strong_20✅_26',['&lt;strong&gt;T009: RX Callback - Receive &amp; Log&lt;/strong&gt; ✅',['../md_PHASE__GUIDE.html#autotoc_md27',1,'']]],
  ['logic_27',['7. Phase 4 – PTT &amp; Buffer Logic',['../md_spec.html#autotoc_md98',1,'']]],
  ['logic_20optimization_28',['⏳ Phase 4: PTT Logic &amp; Optimization',['../md_PHASE__GUIDE.html#autotoc_md41',1,'']]],
  ['logic_20strong_29',['&lt;strong&gt;T016: Mute Logic&lt;/strong&gt;',['../md_PHASE__GUIDE.html#autotoc_md46',1,'']]],
  ['logic_20strong_20✅_30',['&lt;strong&gt;T004: Loopback Logic&lt;/strong&gt; ✅',['../md_PHASE__GUIDE.html#autotoc_md16',1,'']]],
  ['logic_20tối_20ưu_20hóa_31',['logic tối ưu hóa',['../md_TASKS__VI.html#autotoc_md206',1,'⏳ Phase 4: PTT Logic &amp; Tối Ưu Hóa'],['../md_tasks.html#autotoc_md107',1,'🛠️ Phase 4: PTT Logic &amp; Tối Ưu Hóa']]],
  ['logic_20t016_20strong_32',['&lt;strong&gt;Bước 2: Test Mute Logic (T016)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md214',1,'']]],
  ['loopback_33',['loopback',['../md_TASKS__VI.html#autotoc_md112',1,'✅ Phase 1: Nền Tảng &amp; Kiểm Tra Audio Loopback'],['../md_tasks.html#autotoc_md104',1,'✅ Phase 1: Nền Tảng &amp; Kiểm Tra Audio Loopback']]],
  ['loopback_20local_20test_34',['Phase 2: Audio Loopback (Local Test)',['../md_plan.html#autotoc_md73',1,'']]],
  ['loopback_20logic_20strong_20✅_35',['&lt;strong&gt;T004: Loopback Logic&lt;/strong&gt; ✅',['../md_PHASE__GUIDE.html#autotoc_md16',1,'']]],
  ['loopback_20strong_36',['&lt;strong&gt;Test 3: Kiểm tra Audio Loopback&lt;/strong&gt;',['../md_WIRING__GUIDE.html#autotoc_md303',1,'']]],
  ['loopback_20t004_20t005_20strong_37',['&lt;strong&gt;Bước 4: Test Audio Loopback (T004, T005)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md125',1,'']]],
  ['loopback_20test_38',['✅ Phase 1: Foundation &amp; Audio Loopback Test',['../md_PHASE__GUIDE.html#autotoc_md9',1,'']]],
  ['loss_20cao_2010_20strong_39',['&lt;strong&gt;Vấn đề 3: Packet loss cao (&gt;10%)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md172',1,'']]],
  ['loss_20tỷ_20lệ_20mất_20gói_20tin_20strong_40',['&lt;strong&gt;Test 2: Packet Loss (Tỷ lệ mất gói tin)&lt;/strong&gt;',['../md_TASKS__VI.html#autotoc_md158',1,'']]],
  ['luôn_20bằng_200_20strong_41',['luôn bằng 0 strong',['../md_TASKS__VI.html#autotoc_md132',1,'&lt;strong&gt;Vấn đề 2: RMS luôn bằng 0&lt;/strong&gt;'],['../md_WIRING__GUIDE.html#autotoc_md307',1,'&lt;strong&gt;Vấn đề 2: RMS luôn bằng 0&lt;/strong&gt;']]]
];
